package com.jdcr.baseble.constant

import android.bluetooth.BluetoothDevice
import android.bluetooth.BluetoothProfile
import androidx.annotation.IntDef

const val BLE_STATE_DISCONNECTED = BluetoothProfile.STATE_DISCONNECTED
const val BLE_STATE_CONNECTING = BluetoothProfile.STATE_CONNECTING
const val BLE_STATE_CONNECTED = BluetoothProfile.STATE_CONNECTED
const val BLE_STATE_DISCONNECTING = BluetoothProfile.STATE_DISCONNECTING
const val BLE_STATE_CONNECT_EXCEPTION = 4
const val BLE_STATE_SCANNING_START = 5
const val BLE_STATE_SCANNING_END = 6
const val BLE_STATE_SCANNING_FAIL = 7
const val BLE_STATE_NORMAL_DISCONNECT = 8
const val BLE_STATE_EXCEPTION_DISCONNECT = 9
const val BLE_STATE_GATT_EXCEPTION = 10
const val BLE_STATE_REQUEST_CONNECT = 11
const val BLE_STATE_CONNECT_LIMIT = 12
const val BLE_STATE_SERVER_READY = 13

@IntDef(
    BLE_STATE_DISCONNECTED,
    BLE_STATE_CONNECTING,
    BLE_STATE_CONNECTED,
    BLE_STATE_DISCONNECTING,
    BLE_STATE_SCANNING_START,
    BLE_STATE_SCANNING_END,
    BLE_STATE_SCANNING_FAIL,
    BLE_STATE_CONNECT_EXCEPTION,
    BLE_STATE_EXCEPTION_DISCONNECT,
    BLE_STATE_NORMAL_DISCONNECT,
    BLE_STATE_GATT_EXCEPTION,
    BLE_STATE_REQUEST_CONNECT,
    BLE_STATE_CONNECT_LIMIT,
    BLE_STATE_SERVER_READY,
)
@Retention(AnnotationRetention.SOURCE)
annotation class BleServerState